# Generated by Django 6.0.7 on 2026-07-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_id', models.CharField(max_length=64)),
                ('profile_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64)),
                ('metric_type', models.CharField(max_length=32)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='telemetry.device')),
            ],
            options={
                'unique_together': {('device', 'metric_key')},
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
