# Generated by Django 6.0.7 on 2026-07-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
